### PR TITLE
Delete test.txt 3

### PR DESCRIPTION
**Pull request by SergeyShidlovsky**

### CODE REVIEW

**Comment by SergeyShidlovsky** [comment]
Collaborator: Review for this pull request was created. [Link to review](http://47c6d7be.ngrok.io/ui#review:id=5)

**Comment by SergeyShidlovsky** [comment]
Collaborator cannot find remote user mapping for pull request creator, review created by system administrator

**Comment by SergeyShidlovsky** [comment]
Test comment from Github

**Comment by SergeyShidlovsky** [comment]
test comment from Github Two

**Comment by SergeyShidlovsky** [comment]
> Test comment from Github

reply on comment

**Comment by SergeyShidlovsky** [comment]
Yay

**Comment by ghost** [comment]
comment by random user

**Comment by ghost** [comment]
second comment by random user

**Comment by SergeyShidlovsky** [comment]
author comment

**Comment by SergeyShidlovsky** [comment]
author comment second

**Comment by ghost** [comment]
non-author comment

**Comment by ghost** [comment]
second non autor comment

**Comment by ghost** [comment]
Added as collaborator

**Comment by ghost** [comment]
removed as collaborator

**Comment by SergeyShidlovsky** [comment]
Corresponding review in Collaborator has been completed.<br>Author: Administrator.<br>Reviewer: Sergey Shidlovsky.

**Pull request merged**
